(use-package diminish
  :ensure t)

(diminish 'helm-mode)
(diminish 'yas-minor-mode)
(diminish 'eldoc-mode)
(diminish 'company-mode)
(diminish 'projectile-mode)
(diminish 'flyspell-mode)
(diminish 'smartparens-mode)
(diminish 'flycheck-mode)
(diminish 'subword-mode)
(diminish 'visual-hl)
(diminish 'ivy-mode)
(diminish 'anzu-mode)
(diminish 'undo-tree-mode)
(diminish 'whitespace-cleanup-mode)
(diminish 'wrap-mode)
(diminish 'highlight-symbol-mode)
(diminish 'volatile-highlights-mode)
(diminish 'visual-line-mode)
(diminish 'hungry-delete-mode)
(diminish 'auto-revert-mode)

(provide 'core-diminish)
